; MT4 Strategy Tester Configuration

; Enable Experts
ExpertsEnable=true
ExpertsDllImport=true
ExpertsExpImport=false
ExpertsTrades=true

; Strategy Tester Settings
TestExpert=SaveM15Candles
;TestExpertParameters=SaveM15Candles.set
TestSymbol=US100.f
TestPeriod=M15
TestModel=0
TestSpread=0
TestOptimization=false
TestDateEnable=true
TestFromDate=2025.11.07
TestToDate=2025.11.11
;TestReport=RandomTrader_Report_20251112_161811
TestReplaceReport=true
TestShutdownTerminal=false
TestVisualEnable=false